ci: added build check by by running it for some time

diff --git a/.github/workflows/buildv2.yml b/.github/workflows/buildv2.yml
--- a/.github/workflows/buildv2.yml
+++ b/.github/workflows/buildv2.yml
@@ -41,9 +41,22 @@ jobs:
         with:
           version: latest
 
-      - name: Build Docker images with Docker Compose
+      - name: Build and Run Docker images with Docker Compose
         run: |
-          docker compose -f docker-compose.prod.yml build
+          docker compose -f docker-compose.prod.yml up -d --build
+
+      - name: Wait for 30 seconds
+        run: sleep 30
+
+      - name: Check container statuses and logs
+        run: |
+          docker compose ps
+
+          if [[ $(docker compose ps -q | xargs docker inspect -f '{{.State.Status}}' | wc -l) -lt 1 ]]; then
+            echo "One or more containers failed to start." && exit 1
+          fi
+
+          docker compose logs
 
       # Uncomment for debugging
       # - name: SSH into runner (tmate session)
